"""E2E against the example host in web mode (real main framework + real plugins + real Chromium).
Run: an app generated by `fluxplugin init` with examples/plugins copied into plugins/ then: python3 tests/e2e/web_e2e.py [base_url]"""
import sys, os
from playwright.sync_api import sync_playwright, expect

BASE = sys.argv[1] if len(sys.argv) > 1 else "http://127.0.0.1:5173"
SHOTS = os.path.join(os.path.dirname(__file__), "../../docs/screenshots")
errors = []

with sync_playwright() as p:
    b = p.chromium.launch()
    page = b.new_page(viewport={"width": 1100, "height": 720})
    page.on("pageerror", lambda e: errors.append(str(e)))
    page.goto(BASE); page.wait_for_selector("[data-testid=toolbar]")

    side = page.locator(".side")
    for label in ["Students", "Stats", "Analytics", "Plugins"]:
        expect(side.get_by_text(label, exact=True)).to_be_visible()            # menus come from plugin routes
    expect(page.get_by_test_id("dashboard-widget")).to_be_visible()             # slot contribution
    expect(page.get_by_test_id("students-badge")).to_be_visible()               # header slot
    assert page.locator("[data-testid=toolbar] button").all_inner_texts() == ["New student", "Refresh data"]  # priority order
    page.screenshot(path=f"{SHOTS}/dashboard.png")

    # custom title bar: application menu (host + plugins), search providers, notifications, theme
    tb = page.get_by_test_id("titlebar")
    assert tb.locator(".flux-menubar > .flux-menu > button").all_inner_texts() == ["Go", "View", "Help"]
    page.get_by_test_id("notify").click(); expect(page.get_by_test_id("toasts")).to_contain_text("Hello from the host")
    expect(page.get_by_test_id("bell-count")).to_be_visible()
    before = page.evaluate("document.documentElement.getAttribute('data-theme')")
    page.get_by_test_id("theme-toggle").click()
    assert page.evaluate("document.documentElement.getAttribute('data-theme')") != before
    page.get_by_test_id("theme-toggle").click()
    page.fill("[data-testid=searchbox] input", "stats"); expect(page.locator(".flux-search-results")).to_contain_text("Stats"); page.keyboard.press("Escape")

    page.get_by_test_id("dashboard-widget").get_by_role("button").click()       # usePluginState
    expect(page.get_by_test_id("dashboard-widget")).to_contain_text("Clicked 1 times")

    page.get_by_text("Create item “  Ada  ”").click()                        # hooks: before + transform
    expect(page.get_by_test_id("hook-result")).to_contain_text('"name":"Ada"')
    expect(page.get_by_test_id("hook-result")).to_contain_text("normalizedBy")
    page.get_by_text("Create empty item").click()                            # hook veto
    expect(page.get_by_test_id("hook-result")).to_contain_text("cancelled by a hook")

    page.evaluate("location.hash='#/stats'"); page.wait_for_selector("[data-testid=stats-page]")
    expect(page.get_by_test_id("students")).to_have_text("12")                  # renderer -> validated IPC -> main
    page.get_by_text("Add 5 students").click()
    expect(page.get_by_test_id("students")).to_have_text("17")
    expect(page.get_by_test_id("live")).to_have_text("17", timeout=8000)        # main -> renderer push
    assert page.evaluate("typeof window.plugins.stats.get") == "function"       # window.plugins from preload manifest
    page.screenshot(path=f"{SHOTS}/stats.png")

    page.evaluate("location.hash='#/students'"); page.wait_for_selector("[data-testid=students-page]")
    expect(page.locator(".flux-breadcrumbs")).to_contain_text("Students"); expect(page.get_by_test_id("students-layout")).to_be_visible()

    page.keyboard.press("Control+k"); expect(page.locator(".flux-palette")).to_be_visible()
    page.fill(".flux-palette-input", "refresh dash")
    expect(page.locator(".flux-palette-item")).to_have_count(1)
    page.screenshot(path=f"{SHOTS}/command-palette.png"); page.keyboard.press("Escape")

    page.evaluate("location.hash='#/plugins'"); page.wait_for_selector("[data-plugin='com.example.stats']")
    page.screenshot(path=f"{SHOTS}/plugin-manager.png")
    page.locator("[data-plugin='com.example.stats']").get_by_text("Details").click()
    expect(page.get_by_test_id("plugin-details")).to_contain_text("Settings")   # config form from schema
    expect(page.get_by_test_id("plugin-readme")).to_contain_text("What you get")   # detailed description (Markdown)
    assert page.locator("[data-testid^=icon-]").first.evaluate("e=>e.naturalWidth>0")  # plugin icon served from assets/
    page.screenshot(path=f"{SHOTS}/plugin-details.png")

    page.locator("[data-plugin='com.example.students']").get_by_text("Details").click()
    expect(page.get_by_test_id("plugin-video")).to_have_attribute("src", "https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ")  # video embed
    page.screenshot(path=f"{SHOTS}/plugin-video.png")
    # Disable a plugin live: its route, menu and slot disappear without reloading the page.
    page.locator("[data-plugin='com.example.dashboard']").get_by_text("Disable").click()
    expect(page.locator(".side").get_by_text("Analytics", exact=True)).to_have_count(0)
    page.evaluate("location.hash='#/'"); page.wait_for_selector("[data-testid=toolbar]")
    expect(page.get_by_test_id("dashboard-widget")).to_have_count(0)
    page.evaluate("location.hash='#/plugins'")
    page.locator("[data-plugin='com.example.dashboard']").get_by_text("Enable").click()
    page.evaluate("location.hash='#/'")
    expect(page.get_by_test_id("dashboard-widget")).to_be_visible(timeout=5000)  # and comes back

    b.close()
assert not errors, errors
print("E2E OK")
